export const palette = {
  primary: '#2E7D32',
  primaryLight: '#4CAF50',
  primaryContainer: '#E8F5E9',
  secondary: '#8D6E63',
  secondaryContainer: '#EFEBE9',
  tertiary: '#F9A825',
  background: '#FAFAFA',
  surface: '#FFFFFF',
  surfaceVariant: '#F5F5F5',
  outline: '#E0E0E0',
  outlineVariant: '#EEEEEE',
  text: '#212121',
  textMuted: '#616161',
  disabled: '#9E9E9E',
  hint: '#BDBDBD',
  success: '#2E7D32',
  warning: '#F57C00',
  error: '#D32F2F',
  info: '#0288D1',
  white: '#FFFFFF',
  black: '#101418',
} as const;

export const lightColors = {
  primary: palette.primary,
  primaryLight: palette.primaryLight,
  primaryContainer: palette.primaryContainer,
  secondary: palette.secondary,
  secondaryContainer: palette.secondaryContainer,
  accent: palette.tertiary,
  background: palette.background,
  surface: palette.surface,
  surfaceVariant: palette.surfaceVariant,
  text: palette.text,
  textMuted: palette.textMuted,
  disabled: palette.disabled,
  hint: palette.hint,
  border: palette.outline,
  divider: palette.outlineVariant,
  success: palette.success,
  warning: palette.warning,
  error: palette.error,
  info: palette.info,
} as const;

export const darkColors = {
  primary: '#81C784',
  primaryLight: '#A5D6A7',
  primaryContainer: '#163D1A',
  secondary: '#D7CCC8',
  secondaryContainer: '#3E2723',
  accent: '#FFD54F',
  background: '#101411',
  surface: '#181C19',
  surfaceVariant: '#232823',
  text: '#F5F5F5',
  textMuted: '#C8CEC9',
  disabled: '#8A918B',
  hint: '#717971',
  border: '#3B433C',
  divider: '#2C332D',
  success: '#81C784',
  warning: '#FFB74D',
  error: '#EF9A9A',
  info: '#4FC3F7',
} as const;
