import { MD3DarkTheme, MD3LightTheme } from 'react-native-paper';

import { darkColors, lightColors } from '@/theme/colors';

const fontConfig = {
  displayLarge: {
    fontSize: 40,
    lineHeight: 48,
    fontWeight: '700',
    letterSpacing: 0,
  },
  displayMedium: {
    fontSize: 34,
    lineHeight: 42,
    fontWeight: '700',
    letterSpacing: 0,
  },
  headlineLarge: {
    fontSize: 30,
    lineHeight: 38,
    fontWeight: '700',
    letterSpacing: 0,
  },
  headlineMedium: {
    fontSize: 26,
    lineHeight: 34,
    fontWeight: '700',
    letterSpacing: 0,
  },
  headlineSmall: {
    fontSize: 22,
    lineHeight: 30,
    fontWeight: '700',
    letterSpacing: 0,
  },
  titleLarge: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '700',
    letterSpacing: 0,
  },
  titleMedium: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    letterSpacing: 0,
  },
  titleSmall: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
    letterSpacing: 0,
  },
  bodyLarge: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '400',
    letterSpacing: 0,
  },
  bodyMedium: {
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '400',
    letterSpacing: 0,
  },
  bodySmall: {
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '400',
    letterSpacing: 0,
  },
  labelLarge: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
    letterSpacing: 0,
  },
  labelMedium: {
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '700',
    letterSpacing: 0,
  },
  labelSmall: {
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0,
  },
} as const;

export const designTokens = {
  spacing: {
    xxs: 4,
    xs: 8,
    sm: 12,
    md: 16,
    lg: 20,
    xl: 24,
    '2xl': 32,
    '3xl': 40,
    '4xl': 48,
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    pill: 999,
  },
  touch: {
    min: 44,
    comfortable: 48,
    large: 52,
  },
  elevation: {
    card: 1,
    raised: 2,
    floating: 3,
  },
} as const;

export const appLightTheme = {
  ...MD3LightTheme,
  roundness: designTokens.radius.md,
  fonts: {
    ...MD3LightTheme.fonts,
    ...fontConfig,
  },
  colors: {
    ...MD3LightTheme.colors,
    primary: lightColors.primary,
    onPrimary: '#FFFFFF',
    primaryContainer: lightColors.primaryContainer,
    onPrimaryContainer: lightColors.primary,
    secondary: lightColors.secondary,
    onSecondary: '#FFFFFF',
    secondaryContainer: lightColors.secondaryContainer,
    onSecondaryContainer: '#3E2723',
    tertiary: lightColors.accent,
    onTertiary: '#212121',
    tertiaryContainer: '#FFF8E1',
    onTertiaryContainer: '#4A3300',
    background: lightColors.background,
    onBackground: lightColors.text,
    surface: lightColors.surface,
    onSurface: lightColors.text,
    surfaceVariant: lightColors.surfaceVariant,
    onSurfaceVariant: lightColors.textMuted,
    surfaceDisabled: '#F1F1F1',
    onSurfaceDisabled: lightColors.disabled,
    outline: lightColors.border,
    outlineVariant: lightColors.divider,
    error: lightColors.error,
    onError: '#FFFFFF',
    errorContainer: '#FFEBEE',
    onErrorContainer: lightColors.error,
    inverseSurface: '#303030',
    inverseOnSurface: '#F5F5F5',
    inversePrimary: '#A5D6A7',
    elevation: {
      ...MD3LightTheme.colors.elevation,
      level0: 'transparent',
      level1: '#FFFFFF',
      level2: '#FAFAFA',
      level3: '#F5F5F5',
      level4: '#F5F5F5',
      level5: '#EEEEEE',
    },
    backdrop: 'rgba(33, 33, 33, 0.36)',
    success: lightColors.success,
    warning: lightColors.warning,
    info: lightColors.info,
  },
};

export const appDarkTheme = {
  ...MD3DarkTheme,
  roundness: designTokens.radius.md,
  fonts: {
    ...MD3DarkTheme.fonts,
    ...fontConfig,
  },
  colors: {
    ...MD3DarkTheme.colors,
    primary: darkColors.primary,
    onPrimary: '#102A14',
    primaryContainer: darkColors.primaryContainer,
    onPrimaryContainer: '#D7F5D7',
    secondary: darkColors.secondary,
    onSecondary: '#2A1B17',
    secondaryContainer: darkColors.secondaryContainer,
    onSecondaryContainer: '#EFEBE9',
    tertiary: darkColors.accent,
    onTertiary: '#3D2A00',
    tertiaryContainer: '#4A3900',
    onTertiaryContainer: '#FFE082',
    background: darkColors.background,
    onBackground: darkColors.text,
    surface: darkColors.surface,
    onSurface: darkColors.text,
    surfaceVariant: darkColors.surfaceVariant,
    onSurfaceVariant: darkColors.textMuted,
    surfaceDisabled: '#252B26',
    onSurfaceDisabled: darkColors.disabled,
    outline: darkColors.border,
    outlineVariant: darkColors.divider,
    error: darkColors.error,
    onError: '#3B0908',
    errorContainer: '#5F1715',
    onErrorContainer: '#FFDAD6',
    inverseSurface: '#ECEFEB',
    inverseOnSurface: '#1A1F1B',
    inversePrimary: lightColors.primary,
    elevation: {
      ...MD3DarkTheme.colors.elevation,
      level0: 'transparent',
      level1: '#1D221E',
      level2: '#232923',
      level3: '#293029',
      level4: '#2C342D',
      level5: '#303930',
    },
    backdrop: 'rgba(0, 0, 0, 0.5)',
    success: darkColors.success,
    warning: darkColors.warning,
    info: darkColors.info,
  },
};

export type AppTheme = typeof appLightTheme;
