const { lightColors, darkColors } = require('./src/theme/colors');

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./App.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        brand: lightColors.primary,
        'brand-light': lightColors.primaryLight,
        'brand-container': lightColors.primaryContainer,
        secondary: lightColors.secondary,
        'secondary-container': lightColors.secondaryContainer,
        accent: lightColors.accent,
        canvas: lightColors.background,
        surface: lightColors.surface,
        'surface-variant': lightColors.surfaceVariant,
        outline: lightColors.border,
        divider: lightColors.divider,
        ink: lightColors.text,
        muted: lightColors.textMuted,
        disabled: lightColors.disabled,
        hint: lightColors.hint,
        danger: lightColors.error,
        success: lightColors.success,
        warning: lightColors.warning,
        info: lightColors.info,
        'dark-brand': darkColors.primary,
        'dark-brand-light': darkColors.primaryLight,
        'dark-brand-container': darkColors.primaryContainer,
        'dark-secondary': darkColors.secondary,
        'dark-secondary-container': darkColors.secondaryContainer,
        'dark-accent': darkColors.accent,
        'dark-canvas': darkColors.background,
        'dark-surface': darkColors.surface,
        'dark-surface-variant': darkColors.surfaceVariant,
        'dark-outline': darkColors.border,
        'dark-divider': darkColors.divider,
        'dark-ink': darkColors.text,
        'dark-muted': darkColors.textMuted,
        'dark-disabled': darkColors.disabled,
        'dark-hint': darkColors.hint,
      },
      borderRadius: {
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        pill: '999px',
      },
      spacing: {
        xxs: '4px',
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '20px',
        xl: '24px',
        '2xl': '32px',
        '3xl': '40px',
        '4xl': '48px',
      },
      minHeight: {
        touch: '44px',
        button: '48px',
        buttonLarge: '52px',
      },
    },
  },
  plugins: [],
};
